spring:
  rabbitmq:
    port: 5672
    stomp-port: 61613
    host: localhost
    virtual-host: /
    username: guest
    password: guest
    system:
      username: guest
      password: guest
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/malang
    username: root
    password: 'root'
  data:
    redis:
      port: 6379
      host: localhost
cloud:
  aws:
    s3:
      bucket: stackers.bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ENC(unXu+pIUrzXUv7abvtqr803jUsWrrzJ+jyZzcU5iKQs=)
      secret-key: ENC(ASwAeKvdZ6IffS3T3vRYpjI06gS2/63FnWpXENeU6ucpjcp7/Ftki7LabKNR5+ddHLBaGYw11sA=)