spring:
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    port: 5672
    stomp-port: 61613
    host: localhost
    virtual-host: /
    username: guest
    password: guest
    system:
      username: guest
      password: guest
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/malang
    username: root
    password: '1234'